name: 1. CI - Test & Security

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # ==============================
  # Backend: Unit Tests (Maven)
  # ==============================
  backend-test:
    name: Backend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Verify Maven Installation
        run: mvn -v

      - name: Run Backend Tests
        run: mvn clean test --batch-mode

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-results
          path: backend/target/surefire-reports/

  # ==============================
  # Frontend: Unit Tests (React)
  # ==============================
  frontend-test:
    name: Frontend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Run Frontend Tests
        run: npm test -- --watchAll=false

      - name: Upload Test Coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-test-coverage
          path: frontend/coverage/

  # ==============================
  # Security: Vulnerability Scanning
  # ==============================
  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest
    needs: [backend-test, frontend-test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Trivy Scan Backend ---
      - name: Run Trivy Vulnerability Scan (Backend)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './backend'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      # --- Trivy Scan Frontend ---
      - name: Run Trivy Vulnerability Scan (Frontend)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './frontend'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      # --- Optional: Save Scan Reports ---
      - name: Save Trivy Scan Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-reports
          path: |
            ./backend
            ./frontend

      # --- Notify Success ---
      - name: CI Success Flag
        if: success()
        run: |
          echo "✅ CI & Security checks passed successfully."
          echo "CI_SUCCESS=true" >> $GITHUB_ENV
