name: 2. CD - Build, Push & Deploy to Azure

on:
  workflow_run:
    workflows: ["1. CI - Test & Security"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    name: Build, Push & Deploy
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    env:
      ACR_NAME: ${{ secrets.ACR_NAME }}
      RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
      FRONTEND_APP: ${{ secrets.FRONTEND_APP }}
      BACKEND_APP: ${{ secrets.BACKEND_APP }}
      FRONTEND_IMAGE: ${{ secrets.FRONTEND_IMAGE }}
      BACKEND_IMAGE: ${{ secrets.BACKEND_IMAGE }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # -----------------------------------
      # Authenticate with Azure
      # -----------------------------------
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ env.AZURE_CREDS }}

      - name: Log in to ACR
        run: az acr login --name $ACR_NAME

      # -----------------------------------
      # Build & Push Docker Images
      # -----------------------------------
      - name: Build & Push Frontend image
        run: |
          docker build -t $ACR_NAME.azurecr.io/burgerbuilder-frontend:latest ./frontend
          docker push $ACR_NAME.azurecr.io/burgerbuilder-frontend:latest

      - name: Build & Push Backend image
        run: |
          docker build -t $ACR_NAME.azurecr.io/burgerbuilder-backend:latest ./backend
          docker push $ACR_NAME.azurecr.io/burgerbuilder-backend:latest

      # -----------------------------------
      # Deploy Updated Images to ACA
      # -----------------------------------
      - name: Deploy Frontend to ACA
        run: |
          az containerapp update \
            --name $FRONTEND_APP \
            --resource-group $RESOURCE_GROUP \
            --image $FRONTEND_IMAGE \
            --query properties.latestRevisionFqdn

      - name: Deploy Backend to ACA
        run: |
          az containerapp update \
            --name $BACKEND_APP \
            --resource-group $RESOURCE_GROUP \
            --image $BACKEND_IMAGE \
            --query properties.latestRevisionFqdn

      - name: Deployment Success Message
        if: success()
        run: echo "✅ Successfully deployed both containers to Azure Container Apps!"
